server:
  servlet:
    context-path: "/api"
  port: 8444

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_api_db
    username: root
    password: 123456
