
spring:
  profiles:
      active: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            exposed-headers: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin   # 响应头去重




openapi:
  gateway:
    white-list: 192.168.1.3
