server:
  port: 8445


spring:
  cloud:
    gateway:
      routes:
        - id: api_interface_route
          uri: http://127.0.0.1:8444
          predicates:
            - Path=/public_api/**
        - id: open_api_controller_route
          uri: http://127.0.0.1:8443
          predicates:
            - Path=/controller/**

      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            exposed-headers: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin   # 响应头去重
dubbo:
  application:
    name: dubbo-springboot-gateway-consumer
    logger: slf4j
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  protocol:
    name: tri
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.5.100:8848?username=nacos&password=nacos

