spring:
  application:
    name: open-api-controller
  profiles:
    active: prod
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


server:
  servlet:
    context-path: "/controller"


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印sql
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的字段名
      logic-delete-value: 1
      logic-not-delete-value: 0

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.forty
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


# 自定义配置
setting:
  salt: forty
  secret-key: 55s9q11a!!4)s,1aA@DF(ScACX)A__=-sczc)dkD987s230a==


